# This is a basic workflow to help you get started with Actions

name: CI-CD Pipeline
env:
  EB_PACKAGE_S3_BUCKET_NAME: "435hgvghgvhvhvghghgvhgv"
  EB_APPLICATION_NAME: "flask-app"
  EB_ENVIRONMENT_NAME : "Flask-app-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-1"

on: 
  push:
   branches:  [master]
     
jobs:
   my_ci_part:
      runs-on: ubuntu-latest
      
      steps:
      - name: Git clone out repo
      - uses: action/checkout@v1
      
      
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} 
      
